### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by ewilligers** [Motion-Path-Polyfill/motion-path-js#29]
We should give steps to clone the polyfill, and to build and run the tests.

Perhaps assume the reader starts with only a new Goobuntu install.

**Comment by ewilligers** [comment]
The following steps work on a fresh install.

**Install node**
Download the current version of node and npm from [nodejs.org](https://nodejs.org/en/)
Add the directory containing node and npm to your path.

**Clone motion-path-js**
$ git clone https://github.com/Motion-Path-Polyfill/motion-path-js.git
$ cd motion-path-js

**Get dependencies and build tools**
$ git submodule update --init --recursive
$ npm install
$ npm install -g grunt grunt-cli

**Build and run tests**
$ npm test

**Use the polyfill**
Add third_party/web-animations-js/web-animations.dev.js and index.min.js to your web page.
Include offset-position, offset-path, offset-distance, offset-rotate and offset-anchor in your keyframes when calling element.animate.

**Comment by alancutter** [comment]
index.min.js sounds too generic, it should probably be called
motion-path-polyfill.min.js or something.
